version: '3.0.0'
services:
    api:
        # image: semoleg1986/nodejs2023q2-service
        build: 
            dockerfile: Dockerfile
            context: .
        depends_on:
            - postgres
        environment:
            DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
            NODE_ENV: development
            PORT: ${PORT}
        ports:
            - "${PORT}:${PORT}"
        networks:
            - mynetwork
        restart: always
    postgres:
        build:
            context: ./src/database
            dockerfile: Dockerfile
        ports:
            - "35000:5432"
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - mynetwork
        restart: always
networks:
    mynetwork:
        driver: bridge