version: '3.0.0'
services:
    api:
        # image: semoleg1986/nodejs2023q2-service
        build: 
            dockerfile: Dockerfile
            context: .
            target: development
            args:
                - DATABASE_URL=${DATABASE_URL}
        depends_on:
            postgres:
                condition: service_healthy
        container_name: my_nest_app
        volumes:
            - ./src:/usr/src/app/src 
        environment:
            DATABASE_URL: ${DATABASE_URL}
            NODE_ENV: development
            PORT: ${PORT}
        ports:
            - "${PORT}:${PORT}"
        networks:
            - mynetwork
        restart: always
    postgres:
        build:
            context: ./src/database
            dockerfile: Dockerfile
        ports:
            - "35000:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data
        container_name: my_postgres_db
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        networks:
            - mynetwork
        restart: always
        expose:
            - 5432
        healthcheck:
            test: ['CMD', 'pg_isready', '-U', 'user', '-d', 'db']
            interval: 10s
            timeout: 5s
            retries: 5
volumes:
  postgres_data:

networks:
    mynetwork:
        driver: bridge